### ISSUE TITLE
CORS support on profile photos

### ISSUE THREAD

**Issue by buraktamturk** [RandomAPI/Randomapi.com#1]
Hello,

Is it possible to implement CORS on profile photos? It is not possible to get the photo from browser and sent it to another backend right now. For example https://randomuser.me/api/portraits/women/3.jpg

Thanks,

**Comment by keitharm** [comment]
Done! https://github.com/RandomAPI/Randomuser.me-Node/commit/1bf737a0ff1bf8fcbacdf014e7259da33c2f47e9
