### ISSUE TITLE
How can I add a repeat or multiple field ?

### ISSUE THREAD

**Issue by laomao800** [RandomAPI/Randomapi.com#121]
Something like this:

``` js
api = {
    "users|10": [{
        "id": random.numeric(),
        "pass": random.special()
    }]
}
```

will output 10 records in the `users` filed. And use `users|1-10` to output 1 to 10 records .

Or is any other similar way to get this result ? Thanks

**Comment by keitharm** [comment]
I'd personally use a for loop to push X number of users into an array that I could then attach as a property to the API object.

```javascript
let users = [];

// Use this one if you want 1 to 10 users generated
//let num = random.numeric(1, 10);
let num = 10;

for (let i = 0; i < num; i++) {
    users.push({
        id: random.numeric(),
        pass: random.special()
    });
}

api.users = users;
```

**Comment by laomao800** [comment]
I'm using the same way like this. Thanks for the reply.~ 😀
