### ISSUE TITLE
postcode as string

### ISSUE THREAD

**Issue by kibotu** [RandomAPI/Randomapi.com#25]
i believe postalcpde should be a string, because of GB has letters in it

**Comment by keitharm** [comment]
Hi @kibotu,

I think you meant for this to be posted in the [randomuser.me repo](https://github.com/RandomAPI/Randomuser.me-Node). Regardless, GB postcodes should already be returned as a string?
It looks like it is working alright for me: http://api.randomuser.me/?nat=gb&inc=location
